//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public static class masal
	{
		public static string loadMasalLevel (int level)
		{
switch(level)
			{
			case 1:
				return 
					"ﻮﺷ ﺖﻋﺎﻤﺟ ﮓﻧﺮﻤﻫ ﺍﻮﺳﺭ ﻱﻮﺸﻧ ﻲﻫﺍﻮﺧ"+
						"\n"+"Harry Collis When in Rome do az the Romans do"+
						"ﻦﮐ ﺖﺤﻴﺼﻧ ﻭﺭ ﻥﺍﺮﮕﻳﺩ ﺪﻌﺑ ﻦﮐ ﺡﻼﺻﺍ ﻮﺗﺩﻮﺧ ﻝﻭﺍ"+
						"\n"+"Do as I say, not as I do";
			case 2:
				return 
					"ﺖﺳﺍ ﻼﻃ ﺪﻨﺑﺮﻤﮐ ﺯﺍ ﺮﺘﻬﺑ ﮏﻴﻧ ﻡﺎﻧ"+
						"\n"+"Bonne renommée vaut mieux que ceinture dorée"+
						"(ﺩﻭﺭ ﻲﻣ ﺩﻮﺧ ﺩﺍﮋﻧ ﻝﺎﺒﻧﺩ ﻪﺑ ﺏﻮﺧ ﮓﺳ)"+
						"\n"+"Bon chien chasse de race";

			case 3:
				return
					"ﺪﻨﻫﺩ ﻲﻤﻧ ﺍﺬﻏ ﺍﺭ ﻪﺑﺮﮔ ﺎﺒﻳﺯ ﺕﺎﻤﻠﮐ ﺎﺑ"+
						"\n"+"Belle parole non pascono i gatti."+
						"ﺪﻧﺭﺍﺩ ﻲﻫﺎﺗﻮﮐ ﻱﺎﻫﺎﭘ ﺎﻫ ﻍﻭﺭﺩ"+
						"\n"+"Le bugie hanno le gambe corte";
			case 4:
				return
					"ﺖﺴﻴﻧ ﺮﻳﺬﭘ ﻥﺎﮑﻣﺍ ﻲﺘﺳﻭﺩ ﺩﺮﻣ ﮏﻳ ﻭ ﻥﺯ ﮏﻳ ﻦﻴﺑ"+
						"\n"+"ﻪﻧ ﻲﺘﺳﻭﺩ ﺎﻣﺍ .ﺖﺴﻫ ﺮﻔﻨﺗ ﻭ ﺱﺎﺴﺣﺍ،ﻖﺸﻋ"+
						"\n"+"entre un hombre y una mujer no hay amistad posible"+
						"\n"+"hay amor, odio, pasi?n, pero no amistad"+
						"ﻥﺩﺮﮐ ﻲﮔﺪﻧﺯ ﺏﻮﺧ ،ﻥﺩﺮﻣ ﺏﻮﺧ ﻱﺍﺮﺑ"+
						"\n"+"para bien morir, bien vivir";
			}
			return"";

		}

	}
}

